name: campuswhisper
description: "Its an university assistant app. With lots of feature, students can easily track information."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.2
  provider: ^6.1.5
  icons_plus: ^5.0.0
  rename: ^3.1.0
  file_picker: ^10.3.2
  syncfusion_flutter_pdf: ^31.1.18
  shimmer: ^3.0.0
  uuid: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/data/course_roadmap.json
